### ISSUE TITLE
failed to insert a record after mongoose minor update 

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [konsumer/mongoose-type-url#15]
mongoose: `5.4.1`
mongoose-type-url: `1.0.5`
error: `this.constructor._checkRequired is not a function`

**Comment by grubshka** [comment]
#16 should fix

**Comment by AlbertHambardzumyan** [comment]
@konsumer 
Is this resolved? 
PR ? 
Landed ?

**Comment by konsumer** [comment]
Should be resolved in `1.0.6`. Let me know if you have more issues.
