### ISSUE TITLE
normalizeurl breaks URLs with ampersands in the query string

### ISSUE THREAD

**Issue by tamias** [konsumer/mongoose-type-url#6]
When storing a URL with ampersands in the query string, the ampersands are percent-encoded by the call to `normalizeUrl` in `Url.prototype.cast`.  This changes the semantics of the URL.

For example, the URL `http://www.example.com/?foo=1&bar=2` is stored as `http://www.example.com/?foo=1%26bar=2` instead.

**Comment by konsumer** [comment]
should be fixed in `v1.0.5`, let me know if you have issues.
